# Generated by Django 3.1.7 on 2021-03-08 16:02

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_tech_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
