# Generated by Django 3.1.7 on 2021-03-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20210308_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='githubUrl',
            field=models.CharField(default='', max_length=200),
        ),
    ]
