# Generated by Django 3.1.7 on 2021-03-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_project_githuburl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='url',
        ),
        migrations.AddField(
            model_name='project',
            name='youtubeUrl',
            field=models.CharField(default='', max_length=200),
        ),
    ]
